/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/9jCloxA6jBR
 */
import { Button } from "@/components/ui/button"
import Link from "next/link"

export function Footer() {
  return (
    <footer className="bg-white">
      <div className="flex justify-between px-4 py-6">
        <div className="flex items-center space-x-4">
          <FlagIcon className="text-[#E11D48] h-8 w-8" />
          <span className="text-xl font-bold text-[#E11D48]">MangaWatch</span>
        </div>
        <div className="flex items-center space-x-4">
          <DiscIcon className="h-6 w-6 text-[#E11D48]" />
          <TwitterIcon className="h-6 w-6 text-[#E11D48]" />
          <FacebookIcon className="h-6 w-6 text-[#E11D48]" />
          <TwitterIcon className="h-6 w-6 text-[#E11D48]" />
        </div>
      </div>
      <div className="border-t border-gray-200 py-4">
        <div className="flex flex-wrap justify-center space-x-2">
          <Button className="bg-[#E11D48] text-white">All</Button>
          <Button className="bg-[#E11D48] text-white">a</Button>
          <Button className="bg-[#E11D48] text-white">b</Button>
          <Button className="bg-[#E11D48] text-white">c</Button>
          <Button className="bg-[#E11D48] text-white">d</Button>
          <Button className="bg-[#E11D48] text-white">e</Button>
          <Button className="bg-[#E11D48] text-white">f</Button>
          <Button className="bg-[#E11D48] text-white">z</Button>
        </div>
        <p className="mt-4 text-center text-sm text-gray-600">Searching manga order by alphabet name a to z.</p>
      </div>
      <div className="border-t border-gray-200 py-4">
        <div className="flex flex-wrap justify-center space-x-2 sm:space-x-8">
          <Link className="text-[#E11D48] my-2" href="#">
            Terms of service
          </Link>
          <Link className="text-[#E11D48] my-2" href="#">
            DMCA
          </Link>
          <Link className="text-[#E11D48] my-2" href="#">
            Contact
          </Link>
          <Link className="text-[#E11D48] my-2" href="#">
            MangaWatch App
          </Link>
        </div>
        <p className="mt-4 text-center text-sm text-gray-600">
          MangaWatch does not store any files on our server, we only linked to the media which is hosted on 3rd party
          services.
        </p>
        <p className="mt-2 text-center text-sm text-gray-600">© MangaWatch.to. All rights reserved.</p>
      </div>
      <div className="flex justify-center py-4">
        <Button className="rounded-full bg-[#E11D48] p-3 text-white">
          <ArrowUpIcon className="h-4 w-4" />
        </Button>
      </div>
    </footer>
  )
}


function FlagIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z" />
      <line x1="4" x2="4" y1="22" y2="15" />
    </svg>
  )
}


function DiscIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <circle cx="12" cy="12" r="2" />
    </svg>
  )
}


function TwitterIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}


function FacebookIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>
  )
}


function ArrowUpIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m5 12 7-7 7 7" />
      <path d="M12 19V5" />
    </svg>
  )
}
