/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/wbLVPTpzn3r
 */


export function tes() {
  return (
    <div className="w-full py-6 space-y-3 md:py-12 lg:space-y-5">
      <div className="container flex flex-col gap-3 px-4 md:gap-5 lg:gap-8 xl:gap-10">
        <div className="space-y-2">
          <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">About Us</h1>
          <p className="max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
            Bringing you the best manga experience.
          </p>
        </div>
        <img
          alt="Team"
          className="mx-auto overflow-hidden rounded-lg object-cover object-center"
          height="300"
          src="/placeholder.svg"
          style={{
            aspectRatio: "1040/300",
            objectFit: "cover",
          }}
          width="1040"
        />
      </div>
    </div>
  )
}
